from typing import Optional

class BankAccount:
    @staticmethod
    def generate(country: str, bank_code: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(country: str, raw: str) -> bool: ...
    @staticmethod
    def format(country: str, raw: str) -> str: ...
    @staticmethod
    def list_countries() -> list[dict]: ...
    @staticmethod
    def is_supported(country: str) -> bool: ...

class PersonalId:
    @staticmethod
    def generate(
        country: str,
        gender: Optional[str] = None,
        year: Optional[int] = None,
    ) -> str: ...
    @staticmethod
    def validate(country: str, code: str) -> bool: ...
    @staticmethod
    def parse(country: str, code: str) -> dict: ...
    @staticmethod
    def list_countries() -> list[dict]: ...
    @staticmethod
    def is_supported(country: str) -> bool: ...

class CreditCard:
    @staticmethod
    def generate(brand: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(number: str) -> bool: ...
    @staticmethod
    def format(brand: str, number: str) -> str: ...
    @staticmethod
    def list_brands() -> list[str]: ...

class CompanyId:
    @staticmethod
    def generate(country: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(country: str, code: str) -> bool: ...
    @staticmethod
    def list_countries() -> list[dict]: ...

class Swift:
    @staticmethod
    def generate(country: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(code: str) -> bool: ...

class DriverLicense:
    @staticmethod
    def generate(country: Optional[str] = None, state: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(country: str, code: str) -> bool: ...
    @staticmethod
    def list_countries() -> list[dict]: ...

class TaxId:
    @staticmethod
    def generate(country: Optional[str] = None, holder_type: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(country: str, code: str) -> bool: ...
    @staticmethod
    def list_countries() -> list[dict]: ...

class Passport:
    @staticmethod
    def generate(country: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(country: str, code: str) -> bool: ...
    @staticmethod
    def list_countries() -> list[dict]: ...

class LegalEntityId:
    @staticmethod
    def generate(country: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(code: str) -> bool: ...

class VatId:
    @staticmethod
    def generate(country: Optional[str] = None) -> dict: ...
    @staticmethod
    def validate(code: str) -> bool: ...
    @staticmethod
    def list_countries() -> list[dict]: ...

def generate_iban(country: Optional[str] = None) -> str: ...
def validate_iban(iban: str) -> bool: ...
def format_iban(iban: str) -> str: ...
def iban_countries() -> list[str]: ...
