use rand::Rng;

use super::AccountResult;

struct GenericInfo {
    code: &'static str,
    country_name: &'static str,
    format_name: &'static str,
    bank_code_len: u8,
    account_min: u8,
    account_max: u8,
}

static GENERIC_COUNTRIES: &[GenericInfo] = &[
    // Asia
    GenericInfo {
        code: "AF",
        country_name: "Afghanistan",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 16,
    },
    GenericInfo {
        code: "AM",
        country_name: "Armenia",
        format_name: "Bank + Account",
        bank_code_len: 5,
        account_min: 10,
        account_max: 16,
    },
    GenericInfo {
        code: "BD",
        country_name: "Bangladesh",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 10,
        account_max: 13,
    },
    GenericInfo {
        code: "BN",
        country_name: "Brunei",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "BT",
        country_name: "Bhutan",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "ID",
        country_name: "Indonesia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 10,
        account_max: 15,
    },
    GenericInfo {
        code: "IR",
        country_name: "Iran",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 10,
        account_max: 18,
    },
    GenericInfo {
        code: "KG",
        country_name: "Kyrgyzstan",
        format_name: "Bank + Account",
        bank_code_len: 5,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "KH",
        country_name: "Cambodia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "KP",
        country_name: "North Korea",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "LA",
        country_name: "Laos",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "LK",
        country_name: "Sri Lanka",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 15,
    },
    GenericInfo {
        code: "MM",
        country_name: "Myanmar",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "MO",
        country_name: "Macau",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "MV",
        country_name: "Maldives",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 13,
    },
    GenericInfo {
        code: "MY",
        country_name: "Malaysia",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 10,
        account_max: 16,
    },
    GenericInfo {
        code: "NP",
        country_name: "Nepal",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 9,
        account_max: 14,
    },
    GenericInfo {
        code: "PH",
        country_name: "Philippines",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 10,
        account_max: 12,
    },
    GenericInfo {
        code: "SY",
        country_name: "Syria",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "TH",
        country_name: "Thailand",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 10,
        account_max: 10,
    },
    GenericInfo {
        code: "TJ",
        country_name: "Tajikistan",
        format_name: "Bank + Account",
        bank_code_len: 5,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "TM",
        country_name: "Turkmenistan",
        format_name: "Bank + Account",
        bank_code_len: 5,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "TW",
        country_name: "Taiwan",
        format_name: "Bank + Branch + Account",
        bank_code_len: 3,
        account_min: 10,
        account_max: 14,
    },
    GenericInfo {
        code: "UZ",
        country_name: "Uzbekistan",
        format_name: "Bank + Account",
        bank_code_len: 5,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "VN",
        country_name: "Vietnam",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 9,
        account_max: 14,
    },
    GenericInfo {
        code: "YE",
        country_name: "Yemen",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    // Americas
    GenericInfo {
        code: "BB",
        country_name: "Barbados",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "BM",
        country_name: "Bermuda",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "BO",
        country_name: "Bolivia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "BS",
        country_name: "Bahamas",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "BZ",
        country_name: "Belize",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "CL",
        country_name: "Chile",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 16,
    },
    GenericInfo {
        code: "CO",
        country_name: "Colombia",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 10,
        account_max: 16,
    },
    GenericInfo {
        code: "CU",
        country_name: "Cuba",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 16,
    },
    GenericInfo {
        code: "CW",
        country_name: "Curacao",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "DM",
        country_name: "Dominica",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "EC",
        country_name: "Ecuador",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 10,
        account_max: 20,
    },
    GenericInfo {
        code: "GD",
        country_name: "Grenada",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "GY",
        country_name: "Guyana",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "HN",
        country_name: "Honduras",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "HT",
        country_name: "Haiti",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "JM",
        country_name: "Jamaica",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "KN",
        country_name: "Saint Kitts and Nevis",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "PA",
        country_name: "Panama",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "PE",
        country_name: "Peru",
        format_name: "CCI",
        bank_code_len: 3,
        account_min: 14,
        account_max: 14,
    },
    GenericInfo {
        code: "PY",
        country_name: "Paraguay",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "SR",
        country_name: "Suriname",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "TT",
        country_name: "Trinidad and Tobago",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "UY",
        country_name: "Uruguay",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 13,
    },
    GenericInfo {
        code: "VC",
        country_name: "Saint Vincent",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "VE",
        country_name: "Venezuela",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 16,
        account_max: 20,
    },
    // Africa
    GenericInfo {
        code: "AO",
        country_name: "Angola",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 11,
        account_max: 17,
    },
    GenericInfo {
        code: "BF",
        country_name: "Burkina Faso",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "BI",
        country_name: "Burundi",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "BJ",
        country_name: "Benin",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "BW",
        country_name: "Botswana",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 13,
    },
    GenericInfo {
        code: "CD",
        country_name: "DR Congo",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "CF",
        country_name: "Central African Republic",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "CG",
        country_name: "Republic of Congo",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "CI",
        country_name: "Cote d'Ivoire",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "CM",
        country_name: "Cameroon",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "CV",
        country_name: "Cape Verde",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "DJ",
        country_name: "Djibouti",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "DZ",
        country_name: "Algeria",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 10,
        account_max: 20,
    },
    GenericInfo {
        code: "ER",
        country_name: "Eritrea",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "ET",
        country_name: "Ethiopia",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 10,
        account_max: 13,
    },
    GenericInfo {
        code: "GA",
        country_name: "Gabon",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "GH",
        country_name: "Ghana",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 13,
    },
    GenericInfo {
        code: "GM",
        country_name: "Gambia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "GN",
        country_name: "Guinea",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "GQ",
        country_name: "Equatorial Guinea",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "GW",
        country_name: "Guinea-Bissau",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "KE",
        country_name: "Kenya",
        format_name: "Bank + Account",
        bank_code_len: 2,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "KM",
        country_name: "Comoros",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "LR",
        country_name: "Liberia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "LS",
        country_name: "Lesotho",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "MA",
        country_name: "Morocco",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 10,
        account_max: 16,
    },
    GenericInfo {
        code: "MG",
        country_name: "Madagascar",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "ML",
        country_name: "Mali",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "MW",
        country_name: "Malawi",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "MZ",
        country_name: "Mozambique",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "NA",
        country_name: "Namibia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "NE",
        country_name: "Niger",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "RW",
        country_name: "Rwanda",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "SL",
        country_name: "Sierra Leone",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "SN",
        country_name: "Senegal",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "SS",
        country_name: "South Sudan",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "SZ",
        country_name: "Eswatini",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "TD",
        country_name: "Chad",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "TG",
        country_name: "Togo",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "TZ",
        country_name: "Tanzania",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "UG",
        country_name: "Uganda",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 14,
    },
    GenericInfo {
        code: "ZM",
        country_name: "Zambia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 8,
        account_max: 13,
    },
    GenericInfo {
        code: "ZW",
        country_name: "Zimbabwe",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 13,
    },
    // Europe (Crown Dependencies - use GB-style sort code format)
    GenericInfo {
        code: "GG",
        country_name: "Guernsey",
        format_name: "Sort Code + Account",
        bank_code_len: 6,
        account_min: 8,
        account_max: 8,
    },
    GenericInfo {
        code: "IM",
        country_name: "Isle of Man",
        format_name: "Sort Code + Account",
        bank_code_len: 6,
        account_min: 8,
        account_max: 8,
    },
    GenericInfo {
        code: "JE",
        country_name: "Jersey",
        format_name: "Sort Code + Account",
        bank_code_len: 6,
        account_min: 8,
        account_max: 8,
    },
    // Oceania
    GenericInfo {
        code: "FJ",
        country_name: "Fiji",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "FM",
        country_name: "Micronesia",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "KI",
        country_name: "Kiribati",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "MH",
        country_name: "Marshall Islands",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "NR",
        country_name: "Nauru",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "PG",
        country_name: "Papua New Guinea",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "PW",
        country_name: "Palau",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "SB",
        country_name: "Solomon Islands",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "TO",
        country_name: "Tonga",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "TV",
        country_name: "Tuvalu",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "VU",
        country_name: "Vanuatu",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "WS",
        country_name: "Samoa",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    // Special
    GenericInfo {
        code: "AQ",
        country_name: "Antarctica",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 8,
        account_max: 12,
    },
    GenericInfo {
        code: "KY",
        country_name: "Cayman Islands",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 10,
    },
    // Caribbean / Atlantic territories
    GenericInfo {
        code: "AG",
        country_name: "Antigua and Barbuda",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "AI",
        country_name: "Anguilla",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "AW",
        country_name: "Aruba",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "BQ",
        country_name: "Caribbean Netherlands",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "FK",
        country_name: "Falkland Islands",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "MS",
        country_name: "Montserrat",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
    GenericInfo {
        code: "SX",
        country_name: "Sint Maarten",
        format_name: "Bank + Account",
        bank_code_len: 4,
        account_min: 7,
        account_max: 12,
    },
    GenericInfo {
        code: "TC",
        country_name: "Turks and Caicos",
        format_name: "Bank + Account",
        bank_code_len: 3,
        account_min: 7,
        account_max: 10,
    },
];

fn find_info(code: &str) -> Option<&'static GenericInfo> {
    GENERIC_COUNTRIES.iter().find(|c| c.code == code)
}

pub fn is_supported(code: &str) -> bool {
    find_info(code).is_some()
}

pub fn generate(code: &str, rng: &mut impl Rng) -> Option<AccountResult> {
    let info = find_info(code)?;

    let bank_code: String = (0..info.bank_code_len)
        .map(|i| {
            if i == 0 {
                (b'0' + rng.gen_range(1..=9u8)) as char
            } else {
                (b'0' + rng.gen_range(0..=9u8)) as char
            }
        })
        .collect();

    let acct_len = if info.account_min == info.account_max {
        info.account_min
    } else {
        rng.gen_range(info.account_min..=info.account_max)
    };
    let account: String = (0..acct_len)
        .map(|_| (b'0' + rng.gen_range(0..=9u8)) as char)
        .collect();

    let formatted = format!("{} {}", bank_code, account);
    let raw = format!("{}{}", bank_code, account);

    Some(AccountResult {
        country_code: code.to_string(),
        country_name: info.country_name.to_string(),
        format_name: info.format_name.to_string(),
        bank_code: Some(bank_code),
        branch_code: None,
        account_number: account,
        check_digits: None,
        formatted,
        raw,
        iban: None,
        valid: true,
    })
}

pub fn validate(code: &str, raw: &str) -> Option<bool> {
    let info = find_info(code)?;
    let total_min = info.bank_code_len + info.account_min;
    let total_max = info.bank_code_len + info.account_max;
    Some(
        raw.len() >= total_min as usize
            && raw.len() <= total_max as usize
            && raw.chars().all(|c| c.is_ascii_digit()),
    )
}

pub fn format(code: &str, raw: &str) -> Option<String> {
    let info = find_info(code)?;
    let split = info.bank_code_len as usize;
    if raw.len() > split {
        Some(format!("{} {}", &raw[..split], &raw[split..]))
    } else {
        Some(raw.to_string())
    }
}

pub fn list_countries() -> Vec<(&'static str, &'static str, &'static str, bool)> {
    GENERIC_COUNTRIES
        .iter()
        .map(|c| (c.code, c.country_name, c.format_name, false))
        .collect()
}
